### ISSUE TITLE
Stripping shortcodes from string

### ISSUE THREAD

**Issue by denniskoster** [webwizo/laravel-shortcodes#1]
Hi,

First of all I'd like to say I absolutely love your package. Just what I needed!

I guess this is more of a feature request, but would it be possible to strip short codes from a string? In some cases you don't want to compile the short codes, but you don't want them to show up either. Would be great to implement such a method in the short code compiler.

Thanks in advance!

**Comment by webwizo** [comment]
I love to hear that you liked it.

Yeah, you are right. It needs a strip shortcodes as well. I will start working on it.

Thanks,
