### ISSUE TITLE
is it possible to use @include('some_page') ? 

### ISSUE THREAD

**Issue by saeed7m** [webwizo/laravel-shortcodes#10]
hi and thank you for great work , 
is it possible to use    @include(some_page')    in shortcode ? 
I mean I want create shortcode like [test]some_page[/test]
that convert to @include('some_page') ... 
thank you again ...

**Comment by lucassmacedo** [comment]
@saeed7m     Shortcode::add('example', function($atts, $content, $name)
          {

            return view('partials/flash');
          });

**Comment by michaellindahl** [comment]
I believe you need to use `Shortcode::register`
