### ISSUE TITLE
How can I use nested code?

### ISSUE THREAD

**Issue by f4ndoq** [webwizo/laravel-shortcodes#16]
How can I use nested shortcode?
for example:
[tabs]
  [tab]Tab 1[/tab]
  [tab]Tab 2[/tab]
[/tabs]

for this example i should define two shortcode?
one: tabs
two: tab
        Shortcode::register('tabs', TabsShortcode::class);
        Shortcode::register('tab', TabShortcode::class);

**and What should be the content of TabsShortcode & TabShortcode?**
please help me 
thank you

**Comment by vipertec** [comment]
register both and give their definition and then use it
Example :- 
In Providers/**ShortcodesServiceProvider**
```
public function register()
{
    Shortcode::register('div', 'App\Shortcodes\CommonShortcode@div');
    Shortcode::register('h1', 'App\Shortcodes\CommonShortcode@h1');
}
```
In Shortcodes/**CommonShortcode**
```
class CommonShortcode 
{
  public function h1($shortcode, $content)
  {
    return '<h1 '. $shortcode->get('class', 'default') .'>' . $content . '</h1>';
  }
  public function div($shortcode, $content)
  {
    return '<div '. $shortcode->get('class', 'default') .'>' . $content . '</div>';
  }
}
```
In **xyz.blade.php**
```
[div]
[h1] Hello World [/h1]
[/div]
```
