### ISSUE TITLE
Argument 2 passed to Webwizo\Shortcodes\View\View::__construct() must be an instance of Illuminate\View\Engines\EngineInterface

### ISSUE THREAD

**Issue by my8mind** [webwizo/laravel-shortcodes#22]
With Laravel 5.6 you get the following error
Argument 2 passed to Webwizo\Shortcodes\View\View::__construct() must be an instance of Illuminate\View\Engines\EngineInterface, instance of Illuminate\View\Engines\CompilerEngine given.
Changing row 6 of Webwizo\Shortcodes\View\View.php to
Argument 2 passed to Webwizo\Shortcodes\View\View::__construct() must be an instance of use Illuminate\Contracts\View\Engine as EngineInterface;
will fix the issue

**Comment by my8mind** [comment]
#

**Comment by marlongichie** [comment]
Still getting this error on 5.6

Do you have a timeline for this fix?

**Comment by my8mind** [comment]
Just try to reinstall the package through composer and everything should
start working fine

Il giorno mer 25 apr 2018 alle 16:05 Marlon Gichie <notifications@github.com>
ha scritto:
