### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by alexjoffroy** [webwizo/laravel-shortcodes#28]
Hi !

Since this commit d95aaf9d41e55d732c31ca528254f30ea345c2a9, the package has auto-discovery for provider and facade. 

Is it possible (or planned) to release it ?

**Comment by webwizo** [comment]
Thanks for the reminder and sorry for delay. 

New version has been released. 

Thanks friend.

**Comment by alexjoffroy** [comment]
No need to be sorry, we're all busy 😉 Thanks for the package and the release !
