### ISSUE TITLE
Question : UI Implementation ?

### ISSUE THREAD

**Issue by Nuranto** [webwizo/laravel-shortcodes#36]
Hello,

Is there some UI implementation for this package to work with tinymce, ckeditor or else ?

( Something like shortcake in wordpress : visual representation in edit box and a modal form to add the shortcode. )

**Comment by professorhaseeb** [comment]
You are saying you want the shortcodes to parse inside TinyMCE editor while it's being edited?

**Comment by shabbarabbas** [comment]
you can use template plugin for TinyMCE  to crate toolbar button for different shortcodes  
https://www.tiny.cloud/docs/plugins/template/
