### ISSUE TITLE
Getting a list of registered shortcodes

### ISSUE THREAD

**Issue by grafikkaos** [webwizo/laravel-shortcodes#5]
Is there a way of getting a list of registered shortcodes with this package?

**Comment by webwizo** [comment]
No, but if you need I can update the code where you can get all registered shortcodes list as well as their attached classes or closures.

**Comment by grafikkaos** [comment]
Hi webwizo,

My apologies for taking a while to reply to this thread.  It would be great if the code can be updated to allow use to get a list of registered shortcodes.  It will definitely come in handy when building a cms.

Apologies for re-opening this thread.
