### ISSUE TITLE
handle the blade view extension. 

### ISSUE THREAD

**Issue by martingg88** [webwizo/laravel-shortcodes#6]
is the possible to include the following for blade view of this shortcode?
I try to include it but it won't show up. 

Your help is appreciated.  Thank You

@section('scripts')

<script></script>

@stop

**Comment by webwizo** [comment]
Hey, I don't understand what you are asking to me. I can do it if you could describe me enough.

Thanks,

**Comment by martingg88** [comment]
I do have the layout with following structure. 

<body>
@yield('body')
</body>

 @yield('scripts')


@yield('body') will include your shortcode. for example ['event-content' /]

['event-content' /] will call the script and return blade view. 

I mean the blade view is possible to include @section('script')dfasf @stop ?

I try include @section('script')dfasf @stop for shortcode blade view and it won't appear into layout. 

You help is much more appreciate.

**Comment by webwizo** [comment]
You can use `view()->composer()` to apply all views by default `->withShortcodes()`

Here I can guide you by code:

Goto AppServiceProvider and in boot() method, please put following code:
`view()->composer('*', function($view) {
    $view->withShortcodes();
});`

And above code apply withShortcodes method on all view.

Try it.

Thanks,
