### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by aios** [webwizo/laravel-shortcodes#60]

**Comment by voicecode-bv** [comment]
Can this please get tagged? :) Thanks!

**Comment by aios** [comment]
@voicecode-bv you can use aios/laravel-shortcodes temporary until @webwizo can make a release

**Comment by webwizo** [comment]
Sorry for delay.. I can release it now

**Comment by aios** [comment]
@webwizo it will be great, sorry for improvisation. i can delete my package.

**Comment by webwizo** [comment]
It's been done. Thank you for your support.

**Comment by aios** [comment]
@webwizo thank you for a great package and release
