### ISSUE TITLE
PHP 8: Required parameter $shortcode follows optional parameter $data

### ISSUE THREAD

**Issue by volkv** [webwizo/laravel-shortcodes#64]
Hi! one thing is preventing migration to PHP 8.0 - optional parameter deprecated syntax
[src/View/View.php:29](https://github.com/webwizo/laravel-shortcodes/blob/6b4b2f4ed5e0d8e5c91d066cbfe273492e342bdc/src/View/View.php#L29)

thanks

**Comment by webwizo** [comment]
Thanks @volkv for your support.

**Comment by browner12** [comment]
Running into the same or a similar issue in https://github.com/webwizo/laravel-shortcodes/blob/master/src/Compilers/Shortcode.php#L35

PHP 8 is throwing a deprecation notice for an optional parameter coming before a required one.
