### ISSUE TITLE
PHP 8: Required parameter $content follows optional parameter $attributes

### ISSUE THREAD

**Issue by recognizerHD** [webwizo/laravel-shortcodes#67]
Running into the same or a similar issue in https://github.com/webwizo/laravel-shortcodes/blob/master/src/Compilers/Shortcode.php#L35

PHP 8 is throwing a deprecation notice for an optional parameter coming before a required one.

_Originally posted by @browner12 in https://github.com/webwizo/laravel-shortcodes/issues/64#issuecomment-748754689_

I find myself running into this as well.

**Comment by hussamhu** [comment]
i have the issue i am using php 8

**Comment by webwizo** [comment]
Let me fix it today. Thank you for notifying ...
