### ISSUE TITLE
Disable compile shortcode inside input, textarea...

### ISSUE THREAD

**Issue by sangnguyenplus** [webwizo/laravel-shortcodes#7]
Hi @webwizo, 
How we can disable compile shortcode for the content in text, textarea... ?
I mean all of theme, because I have many input field and I don't want to compile shortcode inside it.
Please help me check it.
Thanks!

**Comment by webwizo** [comment]
Can you give me any example so that I can check and update it ?

**Comment by sangnguyenplus** [comment]
You are modifying all response views. So in admin area, when edit content's page, I add a shortcode to textarea, then after save, it compiled this shortcode. I don't want to display compiled shortcode in there.
But I can not disabled shortcode in each view. How I can apply for all input, textarea... in admin area ?
Thanks so much!

**Comment by webwizo** [comment]
For all blade view, we use
`view()->composer('*', function($view) { 
    $view->withShortcodes();
});`

but instead of "*" wildcard, you can assign to all front-end views like `view()->composer('front.*')....`

Did you try it?

**Comment by sangnguyenplus** [comment]
I want to use shortcodes in all views, I just want to disable it inside some input field.
Thanks!

**Comment by webwizo** [comment]
I will work on it, and share with you the solution. Meantime, if you find anything new please share with us all :)

Thank you for your support.
