### ISSUE TITLE
support for Laravel 5.1

### ISSUE THREAD

**Issue by pjona** [webwizo/laravel-shortcodes#8]
Hi,

do you plan support Laravel 5.1? Maybe it's good to change in `composer.json`:

```
"illuminate/view": "~5.3",
"illuminate/support": "~5.3",
"illuminate/contracts": "~5.3",
```

to something like this:

```
"illuminate/view": "~5.1|~5.2|~5.3",
"illuminate/support": "~5.1|~5.2|~5.3",
"illuminate/contracts": "~5.1|~5.2|~5.3",
```

and then we can have support for all Laravel 5 versions in one branch. I can prepare PR with this changes.

**Comment by webwizo** [comment]
I think, that's a great idea. I am gonna do this.

Thank you *pjona*

**Comment by pjona** [comment]
I tested on Laravel 5.1 and it works, thanks!
