### ISSUE TITLE
How to pass string as parameter?

### ISSUE THREAD

**Issue by marlongichie** [webwizo/laravel-shortcodes#9]
Hello,

First, thanks for this wonderful package.

Everything seems to be working fine, but when I try to pass a string as a parameter to a shortcode like so:
`[content_block name="Panel List Group"]`

Each word gets escaped and split into an array in the Shortcode function.

So:
```
public function register($shortcode, $content, $compiler, $name)
    {
        print_r($shortcode);
    }

outputs:
[
"name" => "&quot;Panel"
    0 => "List"
    1 => "Group&quot;"
  ]
```

Has anyone else experienced this?

**Comment by webwizo** [comment]
No, it didn't happen before. Let me check and fix this.

And, thank you for your cooperation for making it better :)

**Comment by webwizo** [comment]
It is working fine here, I just simply copy and paste your shortcode and here is a attached result:

<img width="598" alt="screenshot 2017-02-03 09 13 27" src="https://cloud.githubusercontent.com/assets/1593953/22579348/428bcff8-e9f1-11e6-9462-f9d99152ce17.png">
<img width="826" alt="screenshot 2017-02-03 09 13 41" src="https://cloud.githubusercontent.com/assets/1593953/22579351/428e8f04-e9f1-11e6-8ded-cb5130ade480.png">
<img width="672" alt="screenshot 2017-02-03 09 13 50" src="https://cloud.githubusercontent.com/assets/1593953/22579349/428d018e-e9f1-11e6-8622-a550f322e18c.png">
<img width="1072" alt="screenshot 2017-02-03 09 14 00" src="https://cloud.githubusercontent.com/assets/1593953/22579350/428d682c-e9f1-11e6-937e-4fcc2e079520.png">
